# Generated by Django 6.0.2 on 2026-02-13 16:11

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit_card', 'Credit Card'), ('loan', 'Loan'), ('other', 'Other')], max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Enter the routing number digits only.', regex='^\\d{0,9}$')])),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('pending', 'Pending')], default='active', max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit_limit_or_principal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('statement_close_date', models.DateField(blank=True, null=True)),
                ('payment_due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='households.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('account_type', 'name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posted_on', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('payment', 'Payment'), ('charge', 'Charge')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financial.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financial.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='households.household')),
            ],
            options={
                'ordering': ('-posted_on', '-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='financial_account_user_lower_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='financial_category_user_lower_name_unique'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'posted_on', 'created_at', 'id'], name='fin_txn_acct_posted_created_id'),
        ),
    ]
