# Generated by Django 6.0.2 on 2026-02-10 22:04

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

"""Initial Account schema.

Rollback: `python manage.py migrate financial zero` and reload fixtures
(`financial/fixtures/accounts_minimal.json`) to restore deterministic data.
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit_card', 'Credit Card'), ('loan', 'Loan'), ('other', 'Other')], max_length=20)),
                ('number_last4', models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Enter the last four digits or leave this field blank.', regex='^\\d{0,4}$')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('pending', 'Pending')], default='active', max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit_limit_or_principal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('statement_close_date', models.DateField(blank=True, null=True)),
                ('payment_due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('account_type', 'name', 'created_at'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='financial_account_user_lower_name_unique')],
            },
        ),
    ]
