# Generated by Django 6.0.2 on 2026-02-11 00:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("posted_on", models.DateField()),
                ("description", models.CharField(max_length=255)),
                ("direction", models.CharField(choices=[("debit", "Debit"), ("credit", "Credit")], max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="financial.account"),
                ),
            ],
            options={
                "ordering": ("-posted_on", "-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["account", "posted_on", "created_at", "id"],
                        name="fin_txn_acct_posted_created_id",
                    )
                ],
            },
        ),
    ]
