# Generated by Django 6.0.2 on 2026-02-11

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


def backfill_transaction_type(apps, schema_editor):
    Transaction = apps.get_model("financial", "Transaction")

    type_map = {
        ("checking", "credit"): "deposit",
        ("checking", "debit"): "expense",
        ("savings", "credit"): "deposit",
        ("savings", "debit"): "expense",
        ("credit_card", "credit"): "charge",
        ("credit_card", "debit"): "payment",
        ("loan", "credit"): "charge",
        ("loan", "debit"): "payment",
        ("other", "credit"): "charge",
        ("other", "debit"): "payment",
    }

    for transaction in Transaction.objects.select_related("account").filter(transaction_type__isnull=True).iterator():
        account_type = getattr(transaction.account, "account_type", None)
        direction = transaction.direction
        new_type = type_map.get((account_type, direction))
        if new_type:
            transaction.transaction_type = new_type
            transaction.save(update_fields=["transaction_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0002_transaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="routing_number",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="interest_rate",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        models.F("user"),
                        name="financial_category_user_lower_name_unique",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deposit", "Deposit"),
                    ("expense", "Expense"),
                    ("transfer", "Transfer"),
                    ("adjustment", "Adjustment"),
                    ("payment", "Payment"),
                    ("charge", "Charge"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="financial.category",
            ),
        ),
        migrations.RunPython(backfill_transaction_type, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("expense", "Expense"),
                    ("transfer", "Transfer"),
                    ("adjustment", "Adjustment"),
                    ("payment", "Payment"),
                    ("charge", "Charge"),
                ],
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="direction",
        ),
        migrations.RemoveField(
            model_name="account",
            name="number_last4",
        ),
    ]
