# Generated by Django 6.0.2 on 2026-02-11 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_account_transaction_evolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='routing_number',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Enter the routing number digits only.', regex='^\\d{0,9}$')]),
        ),
    ]
