# Generated by Django 6.0.2 on 2026-02-12 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_households(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    Account = apps.get_model('financial', 'Account')
    Transaction = apps.get_model('financial', 'Transaction')
    Household = apps.get_model('financial', 'Household')
    HouseholdMember = apps.get_model('financial', 'HouseholdMember')

    user_households = {}

    for user in User.objects.order_by('id').iterator():
        household = Household.objects.create(
            name=f"{user.username} Household",
            slug=f"{user.username}-{str(user.id).replace('-', '')[:8]}",
            created_by=user,
        )
        HouseholdMember.objects.create(
            household=household,
            user=user,
            role='owner',
            is_primary=True,
        )
        user_households[user.id] = household.id

    for account in Account.objects.select_related('user').iterator():
        household_id = user_households.get(account.user_id)
        if household_id is not None:
            account.household_id = household_id
            account.save(update_fields=['household'])

    for transaction in Transaction.objects.select_related('account').iterator():
        transaction.household_id = transaction.account.household_id
        transaction.save(update_fields=['household'])


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_alter_account_routing_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_households', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='financial.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('household', 'user'), name='financial_householdmember_unique_household_user'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='financial_householdmember_user_single_primary')],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='financial.household'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='financial.household'),
        ),
        migrations.RunPython(backfill_households, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='account',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='financial.household'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='financial.household'),
        ),
    ]
