# Generated by Django 6.0.2 on 2026-02-19 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_monthly_bill_payment_funding_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='payment_due_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
