# Generated by Django 6.0.2 on 2026-02-19 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_alter_account_payment_due_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBillPaymentCalendarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_calendar_id', models.CharField(max_length=255, unique=True)),
                ('google_event_id', models.CharField(db_index=True, max_length=255)),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_payload_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('monthly_bill_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_link', to='financial.monthlybillpayment')),
            ],
        ),
    ]
