# Generated by Django 6.0.2 on 2026-02-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_monthlybillpaymentcalendarlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybillpaymentcalendarlink',
            name='google_calendar_id',
            field=models.CharField(max_length=255),
        ),
    ]
