# Generated by Django 6.0.2 on 2026-02-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_alter_monthlybillpaymentcalendarlink_google_calendar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_token', models.TextField()),
                ('access_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField()),
            ],
            options={
                'verbose_name': 'Google OAuth Token',
                'verbose_name_plural': 'Google OAuth Tokens',
            },
        ),
    ]
