# Generated by Django 6.0.2 on 2026-02-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_googleoauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybillpayment',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID for sync tracking', max_length=255, null=True),
        ),
    ]
