# Generated by Django 6.0.2 on 2026-03-02 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0006_account_household_lower_name_unique"),
        ("financial", "0010_monthlybillpayment_google_event_id"),
    ]

    operations = []
